version: '2'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftp_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-server
    networks:
      ftp-server-network:
        aliases:
          - ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/home/alejandro/data/ftp/data:/home/ftpusers/"
      - "/home/alejandro/data/ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      - FTP_USER_NAME=user
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/user
      - PUBLICHOST=localhost

# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always

networks:
  ftp-server-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.101.0/24
        gateway: 172.21.101.1

